//! `darwinforge init <name>` — scaffold a minimal Objective-C UIKit project.
//!
//! The generated app builds a window and a label in code, so it needs no
//! storyboard, no XIB and no asset catalog — the three things this PoC cannot
//! compile.

use std::path::{Path, PathBuf};

use crate::error::{Error, Result};

/// Files written by `init`: (relative path, contents).
fn template(name: &str, bundle_id: &str) -> Vec<(String, String)> {
    let config = format!(
        r#"# DarwinForge project configuration.

[app]
# Becomes the .app directory name and CFBundleExecutable. No spaces, no ".app".
name = "{name}"
# Reverse-DNS identifier, CFBundleIdentifier.
bundle_id = "{bundle_id}"
# Deployment target; becomes MinimumOSVersion and the -target triple.
min_ios_version = "13.0"
# CFBundleShortVersionString / CFBundleVersion.
version = "1.0"
build = "1"
# 1 = iPhone, 2 = iPad.
device_family = [1, 2]

# Extra Info.plist keys are merged verbatim:
# [app.info_plist]
# ITSAppUsesNonExemptEncryption = false

[build]
# Globs, relative to this file. `**` crosses directories.
sources = ["Sources/**/*.m", "Sources/**/*.c", "Sources/**/*.mm", "Sources/**/*.cpp"]
resources = ["Resources/**/*"]
frameworks = ["UIKit", "Foundation"]
# libraries = ["z"]            # passed to the linker as -lz
# cflags = ["-fobjc-arc"]      # passed to every clang invocation
# ldflags = ["-dead_strip"]    # passed to the linker
# output_dir = "build"         # deterministic outputs land here
# zip = false                  # true = use the external `zip` binary

# Swift is optional; only needed if you add .swift sources.
# [build.swift]
# swift_flags = []
"#
    );

    let main = include_str!("../templates/main.m");

    let readme = r#"# Hello (generated by `darwinforge init`)

Build it:

    darwinforge build --sdk /path/to/iPhoneOS17.4.sdk

Everything under ./build/ is regenerated on each run:

    build/main.o                  compiled objects
    build/Hello.app/              the app bundle
    build/Hello.ipa               the installable archive

Notes
-----
* No storyboard, no XIB, no asset catalog — this PoC cannot compile those, so
  the app builds its window in code instead.
* The signature is ad-hoc (`ldid -S`). See LIMITATIONS.md.
* `Info.plist` carries an empty `UILaunchScreen` dictionary, which is how you ask
  iOS for a plain launch image without a storyboard.
"#;

    vec![
        ("darwinforge.toml".to_string(), config),
        ("Sources/main.m".to_string(), main.to_string()),
        ("README.md".to_string(), readme.to_string()),
        (".gitignore".to_string(), "build/\n".to_string()),
    ]
}

/// Derive the app name from what the user typed on the command line.
///
/// `darwinforge init ~/Hello` and `darwinforge init /tmp/Hello` must both produce
/// an app called `Hello`: the name becomes the `.app` directory name and
/// `CFBundleExecutable`, neither of which may contain a path separator. Taking
/// only the final component is what keeps the generated config valid instead of
/// silently writing `name = "/home/me/Hello"`.
pub fn derive_app_name(input: &str) -> String {
    // Split on both separators: Windows accepts `/` too, and a WSL user may pass
    // a Windows-style path.
    let last = input.rsplit(['/', '\\']).find(|part| !part.is_empty()).unwrap_or("");
    let trimmed = last.trim();
    // Strip a trailing `.app` so `init Hello.app` does not become `Hello.app.app`.
    let without_suffix = trimmed.strip_suffix(".app").unwrap_or(trimmed).trim();
    if without_suffix.is_empty() {
        // The input was only separators (or only `.app`); fall back to something
        // usable rather than emit an empty app name.
        return "App".to_string();
    }
    without_suffix.to_string()
}

/// Sanitise a string into the last component of a reverse-DNS bundle identifier.
///
/// Bundle ids allow letters, digits, hyphens and dots, and are
/// case-insensitive. Everything else — path separators above all — is dropped,
/// so a name typed as a path can never smuggle a separator into `CFBundleIdentifier`.
pub fn sanitize_bundle_component(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for character in input.chars() {
        if character.is_ascii_alphanumeric() || character == '-' {
            out.push(character.to_ascii_lowercase());
        }
        // Anything else (separators, spaces, dots, punctuation) is dropped; a
        // bundle id already has its own dots between components.
    }
    out
}

/// Build a default bundle id from the app name.
pub fn default_bundle_id(app_name: &str) -> String {
    let component = sanitize_bundle_component(app_name);
    if component.is_empty() {
        // Nothing usable survived sanitising; fall back rather than emit an
        // identifier like `com.example.` that iOS would reject.
        "com.example.app".to_string()
    } else {
        format!("com.example.{component}")
    }
}

/// Create a new project directory. Refuses to overwrite an existing one.
pub fn run(name: &str, bundle_id: Option<&str>, parent: &Path, force: bool) -> Result<PathBuf> {
    // The app name is the final path component only; the full argument still
    // decides where the project is created.
    let app_name = derive_app_name(name);
    let project_dir = parent.join(name);
    if project_dir.exists() {
        if !force {
            return Err(Error::Usage(format!("{} already exists", project_dir.display())));
        }
        if project_dir.is_dir() {
            std::fs::remove_dir_all(&project_dir).map_err(|source| {
                Error::io(format!("cannot replace {}", project_dir.display()), source)
            })?;
        }
    }
    std::fs::create_dir_all(&project_dir)
        .map_err(|source| Error::io(format!("cannot create {}", project_dir.display()), source))?;

    let bundle_id = bundle_id.map(str::to_string).unwrap_or_else(|| default_bundle_id(&app_name));

    for (relative, contents) in template(&app_name, &bundle_id) {
        let path = project_dir.join(&relative);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|source| {
                Error::io(format!("cannot create {}", parent.display()), source)
            })?;
        }
        std::fs::write(&path, contents)
            .map_err(|source| Error::io(format!("cannot write {}", path.display()), source))?;
    }

    println!("created {}", project_dir.display());
    for (relative, _) in template(&app_name, &bundle_id) {
        println!("  {}", project_dir.join(relative).display());
    }
    println!();
    println!("app name  {}", app_name);
    println!("bundle id {}", bundle_id);
    println!();
    println!("next: cd {}", project_dir.display());
    println!("     darwinforge build --sdk /path/to/iPhoneOS17.4.sdk");
    Ok(project_dir)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;

    #[test]
    fn template_contains_config_and_sources() {
        let files = template("Hello", "com.example.hello");
        let names: Vec<&str> = files.iter().map(|(path, _)| path.as_str()).collect();
        assert_eq!(names, vec!["darwinforge.toml", "Sources/main.m", "README.md", ".gitignore"]);
    }

    #[test]
    fn generated_config_parses() {
        let config_text = find("darwinforge.toml");
        let config = Config::from_str(&config_text, Path::new("/tmp/Hello")).expect("must parse");
        assert_eq!(config.app.name, "Hello");
        assert_eq!(config.app.bundle_id, "com.example.hello");
        assert_eq!(config.app.min_ios_version, "13.0");
        assert_eq!(config.app_bundle_name(), "Hello.app");
        assert_eq!(config.build.frameworks, vec!["UIKit", "Foundation"]);
    }

    #[test]
    fn generated_source_defines_main() {
        let main = find("Sources/main.m");
        assert!(main.contains("int main("));
        assert!(main.contains("UIApplicationMain"));
        assert!(!main.contains("UIStoryboard"), "template must not reference a storyboard");
        assert!(!main.contains("UILaunchStoryboardName"), "no storyboard launch key");
    }

    fn find(path: &str) -> String {
        template("Hello", "com.example.hello")
            .into_iter()
            .find(|(name, _)| name == path)
            .unwrap_or_else(|| panic!("template contains {path}"))
            .1
    }

    #[test]
    fn init_with_a_path_argument_uses_only_the_final_component() {
        // The reported bug: `init ~/Hello` wrote the whole path into app.name.
        for input in ["/home/me/Hello", "~/Hello", "./Hello", "../Hello", "Hello"] {
            assert_eq!(derive_app_name(input), "Hello", "input {input:?}");
        }
    }

    #[test]
    fn init_handles_windows_style_paths() {
        assert_eq!(derive_app_name(r"C:\Users\me\Hello"), "Hello");
        assert_eq!(derive_app_name(r"C:\Users\me\Hello\"), "Hello");
    }

    #[test]
    fn a_trailing_app_suffix_is_not_doubled() {
        assert_eq!(derive_app_name("Hello.app"), "Hello");
        assert_eq!(derive_app_name("/tmp/Hello.app"), "Hello");
    }

    #[test]
    fn a_name_of_only_separators_falls_back_instead_of_producing_an_empty_name() {
        assert_eq!(derive_app_name("/"), "App");
        assert_eq!(derive_app_name("///"), "App");
        assert_eq!(derive_app_name(".app"), "App");
    }

    #[test]
    fn bundle_components_are_lowercased_and_stripped_of_separators() {
        assert_eq!(sanitize_bundle_component("Hello"), "hello");
        assert_eq!(sanitize_bundle_component("MyApp"), "myapp");
        assert_eq!(sanitize_bundle_component("my-app"), "my-app");
        assert_eq!(sanitize_bundle_component("my app"), "myapp");
        // The security-relevant case: no separator may survive sanitising.
        assert!(!sanitize_bundle_component("a/b").contains('/'));
        assert!(!sanitize_bundle_component(r"a\b").contains('\\'));
        assert!(!sanitize_bundle_component("../../etc/passwd").contains('/'));
    }

    #[test]
    fn default_bundle_ids_are_always_valid() {
        assert_eq!(default_bundle_id("Hello"), "com.example.hello");
        assert_eq!(default_bundle_id("MyApp"), "com.example.myapp");
        assert_eq!(default_bundle_id("my-cool-app"), "com.example.my-cool-app");
        // Degenerate input still produces something iOS will accept.
        let from_separators = default_bundle_id("///");
        assert!(from_separators.starts_with("com.example."));
        assert!(!from_separators.ends_with('.'), "must not end in a bare dot");
    }

    #[test]
    fn a_generated_config_from_a_path_argument_never_contains_a_separator() {
        // End-to-end: what `init ~/Hello` would write.
        let app_name = derive_app_name("/home/me/Hello");
        let bundle_id = default_bundle_id(&app_name);
        let config_text = template(&app_name, &bundle_id)
            .into_iter()
            .find(|(name, _)| name == "darwinforge.toml")
            .expect("config")
            .1;
        assert!(config_text.contains(r#"name = "Hello""#), "got:\n{config_text}");
        assert!(config_text.contains(r#"bundle_id = "com.example.hello""#));
        assert!(!config_text.contains("/home/me"), "no path may leak into the config");

        let config = Config::from_str(&config_text, Path::new("/tmp/Hello")).expect("must parse");
        assert_eq!(config.app.name, "Hello");
        assert_eq!(config.app.bundle_id, "com.example.hello");
        assert_eq!(config.app_bundle_name(), "Hello.app");
    }
}